# Generated by Django 4.1.1 on 2022-09-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_student_bitiruvchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bitiruvchi',
            field=models.BooleanField(),
        ),
    ]
